name: my_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  stomp_dart_client: ^1.0.0

  cupertino_icons: ^1.0.8
  http: ^1.2.1
  flutter_secure_storage: ^9.0.0

  # ▼▼▼ [추가] Firebase & Notification ▼▼▼
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/avatars/